"""add processed file table which will store metadata on the processed file (also holds which ml model processed it)

Revision ID: 69a93b286d37
Revises: 78988b92ffd3
Create Date: 2025-04-07 19:17:36.978645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a93b286d37'
down_revision: Union[str, None] = '78988b92ffd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_file_id', sa.Integer(), nullable=False),
    sa.Column('processed_filename', sa.String(), nullable=False),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['original_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_files')
    # ### end Alembic commands ###
