"""Fixing back_ref error on User model, now using back_populates

Revision ID: ca30ba0c2e7d
Revises: b971ecf9b3fc
Create Date: 2025-03-10 17:38:23.860878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca30ba0c2e7d'
down_revision: Union[str, None] = 'b971ecf9b3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
